# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/dekyll-for-github" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  jekyll
google_analytic_id:
disqus_name:

permalink: /:year/:month/:day/:title:output_ext
paginate: 1
paginate_path: /page/:num

# jekyll seo tag settings
logo: https://picsum.photos/id/1002/800/600
twitter:
  username: jekyllrb

# Build settings
markdown: kramdown
sass:
  style: compressed
